### ISSUE TITLE
simple rollback doesn't seem to roll back transaction

### ISSUE THREAD

**Issue by rogpeppe** [cznic/kv#24]
As I understand the docs, this code should not print any entries
because the added entries were part of a transaction that is
rolled back. But it actually prints x=y - the Set operation
has actually been committed.

What am I doing wrong?

	package main
	
	import (
		"fmt"
		"io"
		"log"
	
		"github.com/cznic/kv"
	)
	
	func main() {
		db, err := kv.CreateMem(&kv.Options{})
		if err != nil {
			log.Fatal("create:", err)
		}
		if err := db.BeginTransaction(); err != nil {
			log.Fatal("begin transaction:", err)
		}
		if err := db.Set([]byte("x"), []byte("y")); err != nil {
			log.Fatal("set:", err)
		}
		if err := db.Rollback(); err != nil {
			log.Fatal("rollback:", err)
		}
		if err := printKeys(db); err != nil {
			log.Fatal("print keys:", err)
		}
	}
	
	func printKeys(db *kv.DB) error {
		enum, err := db.SeekFirst()
		if err != nil {
			return err
		}
		for {
			k, v, err := enum.Next()
			if err == io.EOF {
				break
			}
			if err != nil {
				return err
			}
			fmt.Printf("%s=%s\n", k, v)
		}
		return nil
	}

**Comment by cznic** [comment]
Thanks for the report. Fix follows. Please note that afterwards you'll have to update also `lldb`.

`go get -u github.com/cznic/kv` should do it.

**Comment by cznic** [comment]
More changes and testing reveal that the problem was not fixed properly.

**Comment by cznic** [comment]
@rogpeppe Sorry for the mess, however, I believe now it's finally correct. Please let me know if not.
