### ISSUE TITLE
DB.Delete seems to be unnecessary

### ISSUE THREAD

**Issue by rogpeppe** [cznic/kv#25]
Given that Get returns a nil value when the entry doesn't
exist, then why not run with that and make a nil value exactly the same
as a deleted value? That is, if you do db.Set(key, nil),
it would be the same as db.Delete(key).

This would also make it easy to allow DB.Put to
delete values as well as create and update them - if
upd returns (true, nil, nil).

**Comment by cznic** [comment]
Considering enumerating a DB: A KV pair with a nil value is distinct from KV pairs which were deleted from the DB.

```go
package main

import (
        "fmt"
        "io"
        "log"

        "github.com/cznic/kv"
)

func main() {
        db, err := kv.CreateMem(&kv.Options{})
        if err != nil {
                log.Fatal(err)
        }

        if err := db.Set([]byte("a"), nil); err != nil {
                log.Fatal(err)
        }

        if err := db.Set([]byte("b"), nil); err != nil {
                log.Fatal(err)
        }

        dump(db)
        if err := db.Delete([]byte("a")); err != nil {
                log.Fatal(err)
        }

        fmt.Println("key a deleted")
        dump(db)
}

func dump(db *kv.DB) {
        fmt.Println("dump")
        enum, err := db.SeekFirst()
        if err != nil {
                log.Fatal(err)
        }

        for {
                k, v, err := enum.Next()
                if err == io.EOF {
                        return
                }

                if err != nil {
                        log.Fatal(err)
                }

                fmt.Printf("%s: %s\n", k, v)
        }
}
```

The output is:
```
dump
a: 
b: 
key a deleted
dump
b: 
```

IOW, the proposed change would be backwards incompatible. If desired, I'll accept a PR adding a new method, say `(*DB).Set2(k, v []byte) error`, which will call `Delete(k)` when `v` is nil.

**Comment by rogpeppe** [comment]
I agree that it is currently possible to tell the difference between nil and not there,
but given that it's not possible to tell the difference with Get (and there's really
no particular use for this distinction AFAICS) I would suggest that the distinction
is removed, so the Get documentation (returns nil if no such value exists) becomes true
in all cases.

I would suggest that backwards compatibility is not a huge issue given that
this package is evidently in relatively early stages (cf issue #24) and this
would definitely simplify the API.

**Comment by rogpeppe** [comment]
Perhaps you could incorporate this change as part of a backwardly incompatible API change including the enumerator change?
