### ISSUE TITLE
Seek misfunctions after inserting specific key sequence

### ISSUE THREAD

**Issue by slrz** [cznic/kv#27]
After inserting a specific set of KV pairs in lexicographic key order (sorted with bytes.Compare, as used by the DB), seeking for some key prefixes stops to work (returns io.EOF immediately). Inserting one more KV pair undoes the damage while e.g. closing and reopening the DB does not.

I can reliably produce such state by inserting the first 796 (when sorted by their SHA1 hash) fortunes from the plan9port fortune file, using the SHA1 hash as the key. The value used doesn't seem to matter.

A program demonstrating the issue can be found at:
http://play.golang.org/p/nvBij8buMA
https://gist.github.com/slrz/a80bdbc7af5c0753091f

Actual output:
got: 511 (expected: 511) (for n=795)
got: 0 (expected: 512) (for n=796)
got: 513 (expected: 513) (for n=797)

Expected output:
got: 511 (expected: 511) (for n=795)
got: 512 (expected: 512) (for n=796)
got: 513 (expected: 513) (for n=797)

Enumerating the full DB using SeekFirst still seems to work. Replacing the 0x10 key prefix in the program with 0x09 or 0x11 also shows the expected behaviour.

Neither DB.Verify nor kvaudit report any issues with the DB.

If you don't have plan9port installed, the file referenced in the test program is this one:
https://github.com/9fans/plan9port/raw/ca9ae08876bc9ce2107fac50cf703760ecf10901/lib/fortunes

Go compiler and runtime are today's tip on Linux but trying with go1.4 shows the same behaviour, as does OS X.

**Comment by cznic** [comment]
Please update your local copy of `github.com/cznic/exp` and test. Thank you.

**Comment by slrz** [comment]
Thanks, that resolves the issue.
