### ISSUE TITLE
How to tell missing record from empty one?

### ISSUE THREAD

**Issue by pmezard** [cznic/kv#28]
Hello,

When calling Get() on a missing key it always return nil data. The same thing happens with records with empty value. How do you tell one from another?

Here is a test describing the problem:

  https://github.com/pmezard/kv/commit/28a08e25d5e83f03af9b73609ed94435ae941954

The last two checks currently fail. The empty record can be seeked so it actually exists.

What do you think of changing Get() so that:
- missing records always return nil
- empty records return an empty slice
(This is boltdb behaviour).

I can try to make a PR on lldb if the change is ok for you.

**Comment by cznic** [comment]
AFAICT, this is a bug in lldb. A PR would be welcome, of course ;-)

**Comment by pmezard** [comment]
Fixed by https://github.com/cznic/exp/pull/9
