### ISSUE TITLE
Expose lldb.Filer for advanced usage

### ISSUE THREAD

**Issue by swsnider** [cznic/kv#31]
Can we get a `CreateFromFiler(filer lldb.Filer, opts *Options) (db *DB, err error)`, which allows me to experiment with different kinds of backing storage?

**Comment by cznic** [comment]
@swsnider Please checkout and test branch `issue31` and let me know if it works for you. Will merge only after we agree on the changes. I'm open to suggestions. Looking forward your feedback. Thank you.

**Comment by swsnider** [comment]
Looks like a good start for me, unfortunately, I forgot to mention that I also want/need `OpenFromFiler` as well, and I'd like to be able to indicate somehow that WALs should be written to a temp folder, instead of trying to divine the pathname of the Filer, since my Filer implementation uses a networked filesystem that is not POSIX compliant.

**Comment by swsnider** [comment]
Thanks, BTW!

**Comment by cznic** [comment]
@swsnider PTAL, thanks.

**Comment by swsnider** [comment]
Works like a charm!
